name: maldi3d
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
dependencies:
  - python=3.10.12
  - pip
  - numpy=1.24.4
  - pandas=1.5.3
  - scikit-image=0.22.0
  - matplotlib=3.7.1
  - nibabel=5.1.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - tqdm=4.64.1
  - jupyter=1.1.1
  - pip:
      - opencv-python-headless==4.10.0.84
  
